name: 'Recommendation Experience Publisher'
description: 'Publish your recommendation experiences to Nosto'
author: 'Nosto'
inputs: 
  NOSTO_TOKEN:
    required: true
    description: 'The NOSTO_TOKEN secret'
  TEMPLATE_DIRECTORY:
    required: true
    description: 'The directory containing the templates'
runs:
  using: 'node12'
  main: 'lib/main.js'
