name: 'Recommendation Experience Publisher'
description: 'Publish your recommendation experiences to Nosto'
author: 'Nosto'
branding:
  icon: 'layout'  
  color: 'red'
inputs:
  nosto-token:
    required: true
    description: 'The NOSTO_TOKEN secret'
  template-directory:
    required: true
    description: 'The directory containing the templates'
runs:
  using: 'docker'
  image: 'Dockerfile'
